### ISSUE TITLE
[TPC-H] Dask query 9 raises `RecursionError: maximum recursion depth exceeded`

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/benchmarks#1281] opened 2024-01-26 11:32 UTC

**Comment by milesgranger** [comment] 2024-01-26 12:51
duplicate of https://github.com/coiled/benchmarks/issues/1274 and will be closed by https://github.com/coiled/benchmarks/pull/1277

**Closed by milesgranger** 2024-01-26 12:51 UTC
Labels: bug, tpch
